(function(e){function g(){var d=!1,a=!1;this.stopPropagation=function(){d=!0};this.isPropagationStopped=function(){return d};this.stopImmediatePropagation=function(){a=!0};this.isImmediatePropagationStopped=function(){return a}}function a(){this.__nonDataRow=!0}function f(){this.__group=!0;this.__updated=!1;this.count=0;this.title=this.value=null;this.collapsed=!1;this.totals=null}function m(){this.__groupTotals=!0;this.group=null}function h(){var d=null;this.isActive=function(a){return a?d===a:null!==
d};this.activate=function(a){if(a!==d){if(null!==d)throw"SlickGrid.EditorLock.activate: an editController is still active, can't activate another editController";if(!a.commitCurrentEdit)throw"SlickGrid.EditorLock.activate: editController must implement .commitCurrentEdit()";if(!a.cancelCurrentEdit)throw"SlickGrid.EditorLock.activate: editController must implement .cancelCurrentEdit()";d=a}};this.deactivate=function(a){if(d!==a)throw"SlickGrid.EditorLock.deactivate: specified editController is not the currently active one";
d=null};this.commitCurrentEdit=function(){return d?d.commitCurrentEdit():!0};this.cancelCurrentEdit=function(){return d?d.cancelCurrentEdit():!0}}e.extend(!0,window,{Slick:{Event:function(){var d=[];this.subscribe=function(a){d.push(a)};this.unsubscribe=function(a){for(var e=d.length-1;0<=e;e--)d[e]===a&&d.splice(e,1)};this.notify=function(a,e,h){e=e||new g;h=h||this;for(var f,m=0;m<d.length&&!e.isPropagationStopped()&&!e.isImmediatePropagationStopped();m++)f=d[m].call(h,e,a);return f}},EventData:g,
EventHandler:function(){var d=[];this.subscribe=function(a,e){d.push({event:a,handler:e});a.subscribe(e);return this};this.unsubscribe=function(a,e){for(var h=d.length;h--;)if(d[h].event===a&&d[h].handler===e){d.splice(h,1);a.unsubscribe(e);return}return this};this.unsubscribeAll=function(){for(var a=d.length;a--;)d[a].event.unsubscribe(d[a].handler);d=[];return this}},Range:function(d,a,e,h){void 0===e&&void 0===h&&(e=d,h=a);this.fromRow=Math.min(d,e);this.fromCell=Math.min(a,h);this.toRow=Math.max(d,
e);this.toCell=Math.max(a,h);this.isSingleRow=function(){return this.fromRow==this.toRow};this.isSingleCell=function(){return this.fromRow==this.toRow&&this.fromCell==this.toCell};this.contains=function(d,a){return d>=this.fromRow&&d<=this.toRow&&a>=this.fromCell&&a<=this.toCell};this.toString=function(){return this.isSingleCell()?"("+this.fromRow+":"+this.fromCell+")":"("+this.fromRow+":"+this.fromCell+" - "+this.toRow+":"+this.toCell+")"}},NonDataRow:a,Group:f,GroupTotals:m,EditorLock:h,GlobalEditorLock:new h}});
f.prototype=new a;f.prototype.equals=function(d){return this.value===d.value&&this.count===d.count&&this.collapsed===d.collapsed};m.prototype=new a})(jQuery);(function(e){e.extend(!0,window,{Slick:{Formatters:{YesNo:function(e,a,f){return f?"Yes":"No"},Checkmark:function(e,a,f){return f?"<img src='slickgrids/images/tick.png'>":""},NetworkLogoSmall:function(e,a,f){if(""!=f)return"<img width='25' src='"+f+"'>"},NetworkCallsign:function(e,a,f){e=f.split("|");return'<span title="'+e[1]+'">'+e[0]+"</span>"},NetworkLogoUrlSmall:function(e,a,f){return"<img width='25' src='http://ww2.showseeker.com/logos/thumbnail/"+f+"'>"},DayOfWeek:function(e,a,f){return formatterDayOfWeek(f)},
EPITitle:function(e,a,f){e=f.split("|");return""<e[1]?"<b>"+e[0]+"</b> | <span class='smgrid'>"+e[1]+"</span>":"<b>"+e[0]+"</b>"},StatusIcons:function(e,a,f){e=f.split("|");return"Premiere"==e[0]?'<span style="color:#990000;"><b>Mov Pre</b></span>':"Season Premiere"==e[0]?'<span style="color:#990000;"><b>Sea Pre</b></span>':"Series Premiere"==e[0]?'<span style="color:#990000;"><b>Ser Pre</b></span>':"Season Finale"==e[0]?'<span style="color:#990000;"><b>Sea Fin</b></span>':"Series Finale"==e[0]?'<span style="color:#990000;"><b>Ser Fin</b></span>':
""!=e[1]?'<span style="color:#660066;"><b>Live</b></span>':""!=e[2]?'<span style="color:#006633;"><b>New</b></span>':""},RowCount:function(e,a,f,m){return"total"==m.field?accounting.formatMoney(f):"spotsweek"==m.field?'<div class="fixed-allow">'+f+"</div>":"rate"==m.field?'<div class="fixed-allow">'+accounting.formatMoney(f)+"</div>":0<f?'<div class="fixed-allow">'+f+"</div>":0},ProposalSettings:function(){return'<div onclick="openProposalSettings();" class="ui-icon ui-icon-gear"></div>'},LineType:function(){return"F"},
Money:function(e,a,f,m){num=f;num=isNaN(num)||""===num||null===num?0:num;return"rate"==m.id?'<div class="fixed-allow">$'+parseFloat(num).toFixed(2)+"</div>":"$"+parseFloat(num).toFixed(2)},FormatDate:function(e,a,f){return Date.parse(f).toString("MM/dd/yyyy")},Ratecard:function(e,a,f){return"<span class=ratecard>"+accounting.formatMoney(f)+"</span>"},FormatTime:function(e,a,f){return Date.parse(f).toString("hh:mm tt")},FormatGetKeyword:function(g,a,f){var m=f.toLowerCase(),h="";e.each(searchKeywordsArray,
function(d,e){var a=e.title.toLowerCase(),a=m.search(a);console.log(a);-1!=parseInt(a)&&(h=e.title)});return h},FormatRemove:function(e){return'<div class="deletex"><img src="i/x.png" border=0 onClick="removeRowFromEzSearch('+e+')"></div>'},FormatDateTime:function(e,a,f){return(new Date(f)).toString("MM/dd/yyyy hh:mm tt")},DeleteFromGrid:function(){return'<img src="i/x.png" border=0>'},DeleteFromGridTitle:function(e){return'<div class="deletex"><img src="i/x.png" border=0 onClick=removeArrayElement('+
e+',"title")></div>'}}}})})(jQuery);(function(e){e.extend(!0,window,{Slick:{Editors:{Text:function(g){var a,f;this.init=function(){a=e("<INPUT type=text class='editor-text' onkeypress='validate(event)' />").appendTo(g.container).bind("keydown.nav",function(a){(a.keyCode===e.ui.keyCode.LEFT||a.keyCode===e.ui.keyCode.RIGHT)&&a.stopImmediatePropagation()}).focus().select()};this.destroy=function(){a.remove()};this.focus=function(){a.focus()};this.getValue=function(){return a.val()};this.setValue=function(e){a.val(e)};this.loadValue=function(e){f=
e[g.column.field]||"";a.val(f);a[0].defaultValue=f;a.select()};this.serializeValue=function(){return a.val()};this.applyValue=function(e,a){e[g.column.field]=a};this.isValueChanged=function(){return!(""==a.val()&&null==f)&&a.val()!=f};this.validate=function(){if(g.column.validator){var e=g.column.validator(a.val());if(!e.valid)return e}return{valid:!0,msg:null}};this.init()},Integer:function(g){var a,f;this.init=function(){a=e("<INPUT type=text class='editor-text' />");a.bind("keydown.nav",function(a){(a.keyCode===
e.ui.keyCode.LEFT||a.keyCode===e.ui.keyCode.RIGHT)&&a.stopImmediatePropagation()});a.appendTo(g.container);a.focus().select()};this.destroy=function(){a.remove()};this.focus=function(){a.focus()};this.loadValue=function(e){f=e[g.column.field];a.val(f);a[0].defaultValue=f;a.select()};this.serializeValue=function(){return parseInt(a.val(),10)||0};this.applyValue=function(e,a){e[g.column.field]=a};this.isValueChanged=function(){return!(""==a.val()&&null==f)&&a.val()!=f};this.validate=function(){return isNaN(a.val())?
{valid:!1,msg:"Please enter a valid integer"}:{valid:!0,msg:null}};this.init()},Date:function(g){var a,f,m=!1;this.init=function(){a=e("<INPUT type=text class='editor-calendar'/>");a.appendTo(g.container);a.focus().select();a.datepicker({showOn:"button",buttonImageOnly:!0,buttonImage:"slickgrids/images/calendar.gif",firstDay:1,showTrailingWeek:!1,beforeShow:function(){m=!0},onClose:function(){m=!1}});a.width(a.width()-18)};this.destroy=function(){e.datepicker.dpDiv.stop(!0,!0);a.datepicker("hide");
a.datepicker("destroy");a.remove()};this.show=function(){m&&e.datepicker.dpDiv.stop(!0,!0).show()};this.hide=function(){m&&e.datepicker.dpDiv.stop(!0,!0).hide()};this.position=function(a){m&&e.datepicker.dpDiv.css("top",a.top+30).css("left",a.left)};this.focus=function(){a.focus()};this.loadValue=function(e){f=e[g.column.field];a.val(f);a[0].defaultValue=f;a.select()};this.serializeValue=function(){return a.val()};this.applyValue=function(e,d){e[g.column.field]=d};this.isValueChanged=function(){return!(""==
a.val()&&null==f)&&a.val()!=f};this.validate=function(){return{valid:!0,msg:null}};this.init()},YesNoSelect:function(g){var a,f;this.init=function(){a=e("<SELECT tabIndex='0' class='editor-yesno'><OPTION value='yes'>Yes</OPTION><OPTION value='no'>No</OPTION></SELECT>");a.appendTo(g.container);a.focus()};this.destroy=function(){a.remove()};this.focus=function(){a.focus()};this.loadValue=function(e){a.val((f=e[g.column.field])?"yes":"no");a.select()};this.serializeValue=function(){return"yes"==a.val()};
this.applyValue=function(e,a){e[g.column.field]=a};this.isValueChanged=function(){return a.val()!=f};this.validate=function(){return{valid:!0,msg:null}};this.init()},Checkbox:function(g){var a,f;this.init=function(){a=e("<INPUT type=checkbox value='true' class='editor-checkbox' hideFocus>");a.appendTo(g.container);a.focus()};this.destroy=function(){a.remove()};this.focus=function(){a.focus()};this.loadValue=function(e){(f=e[g.column.field])?a.attr("checked","checked"):a.removeAttr("checked")};this.serializeValue=
function(){return a.attr("checked")};this.applyValue=function(e,a){e[g.column.field]=a};this.isValueChanged=function(){return a.attr("checked")!=f};this.validate=function(){return{valid:!0,msg:null}};this.init()},PercentComplete:function(g){var a,f,m;this.init=function(){a=e("<INPUT type=text class='editor-percentcomplete' />");a.width(e(g.container).innerWidth()-25);a.appendTo(g.container);f=e("<div class='editor-percentcomplete-picker' />").appendTo(g.container);f.append("<div class='editor-percentcomplete-helper'><div class='editor-percentcomplete-wrapper'><div class='editor-percentcomplete-slider' /><div class='editor-percentcomplete-buttons' /></div></div>");
f.find(".editor-percentcomplete-buttons").append("<button val=0>Not started</button><br/><button val=50>In Progress</button><br/><button val=100>Complete</button>");a.focus().select();f.find(".editor-percentcomplete-slider").slider({orientation:"vertical",range:"min",value:m,slide:function(e,d){a.val(d.value)}});f.find(".editor-percentcomplete-buttons button").bind("click",function(){a.val(e(this).attr("val"));f.find(".editor-percentcomplete-slider").slider("value",e(this).attr("val"))})};this.destroy=
function(){a.remove();f.remove()};this.focus=function(){a.focus()};this.loadValue=function(e){a.val(m=e[g.column.field]);a.select()};this.serializeValue=function(){return parseInt(a.val(),10)||0};this.applyValue=function(e,d){e[g.column.field]=d};this.isValueChanged=function(){return!(""==a.val()&&null==m)&&(parseInt(a.val(),10)||0)!=m};this.validate=function(){return isNaN(parseInt(a.val(),10))?{valid:!1,msg:"Please enter a valid positive number"}:{valid:!0,msg:null}};this.init()},LongText:function(g){var a,
f,m,h=this;this.init=function(){var d=e("body");f=e("<DIV style='z-index:10000;position:absolute;background:white;padding:5px;border:2px solid #cccccc; -moz-border-radius:3px; border-radius:3px;'/>").appendTo(d);a=e("<TEXTAREA hidefocus rows=5  id='textEditorLong'>").appendTo(f);e("<DIV style='text-align:right'><BUTTON>Save</BUTTON><BUTTON>Cancel</BUTTON></DIV>").appendTo(f);f.find("button:first").bind("click",this.save);f.find("button:last").bind("click",this.cancel);a.bind("keydown",this.handleKeyDown);
h.position(g.position);a.focus().select()};this.handleKeyDown=function(d){d.which==e.ui.keyCode.ENTER&&d.ctrlKey?h.save():d.which==e.ui.keyCode.ESCAPE?(d.preventDefault(),h.cancel()):d.which==e.ui.keyCode.TAB&&d.shiftKey?(d.preventDefault(),g.grid.navigatePrev()):d.which==e.ui.keyCode.TAB&&(d.preventDefault(),g.grid.navigateNext())};this.save=function(){g.commitChanges()};this.cancel=function(){a.val(m);g.cancelChanges()};this.hide=function(){f.hide()};this.show=function(){f.show()};this.position=
function(d){f.css("top",d.top-5).css("left",d.left-5)};this.destroy=function(){f.remove()};this.focus=function(){a.focus()};this.loadValue=function(d){a.val(m=d[g.column.field]);a.select()};this.serializeValue=function(){return a.val()};this.applyValue=function(d,e){d[g.column.field]=e};this.isValueChanged=function(){return!(""==a.val()&&null==m)&&a.val()!=m};this.validate=function(){return{valid:!0,msg:null}};this.init()}}}})})(jQuery);/*

 (c) 2009-2012 Michael Leibman
 michael{dot}leibman{at}gmail{dot}com
 http://github.com/mleibman/slickgrid

 Distributed under MIT license.
 All rights reserved.

 SlickGrid v2.1

 NOTES:
     Cell/row DOM manipulations are done directly bypassing jQuery's DOM manipulation methods.
     This increases the speed dramatically, but can only be done safely because there are no event handlers
     or data associated with any cell/row DOM nodes.  Cell editors must make sure they implement .destroy()
     and do proper cleanup.

*/
if("undefined"===typeof jQuery)throw"SlickGrid requires jquery module to be loaded";if(!jQuery.fn.drag)throw"SlickGrid requires jquery.event.drag module to be loaded";if("undefined"===typeof Slick)throw"slick.core.js not loaded";
(function(e){e.extend(!0,window,{Slick:{Grid:function(f,m,h,d){function fb(){if(!ua){ua=!0;Cb();Db();var b,c=["borderLeftWidth","borderRightWidth","paddingLeft","paddingRight"],t=["borderTopWidth","borderBottomWidth","paddingTop","paddingBottom"];b=e("<div class='ui-state-default slick-header-column' style='visibility:hidden'>-</div>").appendTo(M);Ua=jc=0;e.each(c,function(c,d){Ua+=parseFloat(b.css(d))||0});e.each(t,function(c,d){jc+=parseFloat(b.css(d))||0});b.remove();var a=e("<div class='slick-row' />").appendTo(Va);
b=e("<div class='slick-cell' id='' style='visibility:hidden'>-</div>").appendTo(a);Rb=Sb=0;e.each(c,function(c,d){Rb+=parseFloat(b.css(d))||0});e.each(t,function(c,d){Sb+=parseFloat(b.css(d))||0});a.remove();La=Math.max(Ua,Rb);M&&M.jquery&&M.attr("unselectable","on").css("MozUserSelect","none").bind("selectstart.ui",function(){return!1});d.enableTextSelectionOnCells||Tb.bind("selectstart.ui",function(b){return e(b.target).is("input,textarea")});O();T();oa();va();jQuery.fn.mousewheel&&-1<d.frozenColumn&&
(!d.frozenBottom&&r?fa.mousewheel(Fc):U.mousewheel(Fc));gb();Wa();M.click(function(b){b.metaKey=b.metaKey||b.ctrlKey;if(!e(b.target).hasClass("slick-resizable-handle")){var c=e(b.target).closest(".slick-header-column");if(c.length&&(c=c.data("column"),c.sortable&&B().commitCurrentEdit())){for(var t=null,a=0;a<V.length;a++)if(V[a].columnId==c.id){t=V[a];t.sortAsc=!t.sortAsc;break}if(b.metaKey&&d.multiColumnSort)t&&V.splice(a,1);else{if(!b.shiftKey&&!b.metaKey||!d.multiColumnSort)V=[];t?0==V.length&&
V.push(t):(t={columnId:c.id,sortAsc:!0},V.push(t))}Ca(V);d.multiColumnSort?j(n.onSort,{multiColumnSort:!0,sortCols:e.map(V,function(b){return{sortCol:h[ga[b.columnId]],sortAsc:b.sortAsc}})},b):j(n.onSort,{multiColumnSort:!1,sortCol:c,sortAsc:t.sortAsc},b)}}});Da();$();for(c=r&&!d.frozenBottom?wa[0]:pa[0];(c=c.parentNode)!=document.body&&null!=c;)if(c==U[0]||c.scrollWidth!=c.clientWidth||c.scrollHeight!=c.clientHeight)t=e(c),hb=hb?hb.add(t):t,t.bind("scroll."+aa,Gc);D.bind("resize.slickgrid",$);Tb.bind("scroll",
Eb);Ub.bind("contextmenu",jd).bind("click",kd).delegate(".slick-header-column","mouseenter",ld).delegate(".slick-header-column","mouseleave",md);ib.bind("scroll",nd);Vb.add(kc).bind("keydown",Hc);Va.bind("keydown",Hc).bind("click",od).bind("dblclick",pd).bind("contextmenu",qd).bind("draginit",rd).bind("dragstart",sd).bind("drag",td).bind("dragend",ud).delegate(".slick-cell","mouseenter",vd).delegate(".slick-cell","mouseleave",wd)}}function Pb(b){for(var c=Ma.length;0<=c;c--)if(Ma[c]===b){Ma[c].destroy&&
Ma[c].destroy();Ma.splice(c,1);break}}function Qb(){for(var b=ha=Ea=0,c=h.length;b<c;b++){var t=h[b].width;-1<d.frozenColumn&&b>d.frozenColumn?Ea+=t:ha+=t}-1<d.frozenColumn?(ha+=1E3,Ea=Math.max(Ea,W)+ha,Ea+=g.width):(ha+=g.width,ha=Math.max(ha,W)+1E3)}function Bb(){var b=jb?W-g.width:W,c=h.length;for(E=qa=0;c--;)-1<d.frozenColumn&&c>d.frozenColumn?qa+=h[c].width:E+=h[c].width;c=E+qa;return d.fullWidthRows?Math.max(c,b):c}function q(b){var c=E,t=qa,e=Bb();if((c=E!==c||qa!==t)||-1<d.frozenColumn||r)pa.width(E),
Qb(),Fa.width(ha),Xa.width(Ea),-1<d.frozenColumn?(kb.width(qa),lb.width(E),mb.css("left",E),Ga.width(E),Na.css("left",E),Ya.width(E),Fb.width(qa),Ha.width(E),nb.width(qa),U.width(E),xa.width(W-E),r&&(ya.width(E),Oa.css("left",E),fa.width(E),Ia.width(W-E),wa.width(E),ob.width(qa))):(lb.width("100%"),Ga.width("100%"),Ya.width("100%"),Ha.width("100%"),U.width("100%"),r&&(fa.width("100%"),wa.width(E))),lc=e>W-g.width;Ic.width(e+(jb?g.width:0));(c||b)&&Za()}function Wa(){function b(){e(this).addClass("ui-state-hover")}
function c(){e(this).removeClass("ui-state-hover")}M.find(".slick-header-column").each(function(){var b=e(this).data("column");b&&j(n.onBeforeHeaderCellDestroy,{node:this,column:b})});Fa.empty();Xa.empty();Qb();Fa.width(ha);Xa.width(Ea);Ha.empty();nb.empty();Wb.find(".slick-headerrow-column").each(function(){var b=e(this).data("column");b&&j(n.onBeforeHeaderRowCellDestroy,{node:this,column:b})});for(var t=0;t<h.length;t++){var a=h[t],l=-1<d.frozenColumn?t<=d.frozenColumn?Fa:Xa:Fa,y=-1<d.frozenColumn?
t<=d.frozenColumn?Ha:nb:Ha,l=e("<div class='ui-state-default slick-header-column' id='"+aa+a.id+"' />").html("<span class='slick-column-name'>"+a.name+"</span>").width(a.width-Ua).attr("title",a.toolTip||"").data("column",a).addClass(a.headerCssClass||"").appendTo(l);(d.enableColumnReorder||a.sortable)&&l.hover(b,c);a.sortable&&l.append("<span class='slick-sort-indicator' />");j(n.onHeaderCellRendered,{node:l[0],column:a});d.showHeaderRow&&(y=e("<div class='ui-state-default slick-headerrow-column l"+
t+" r"+t+"'></div>").data("column",a).appendTo(y),j(n.onHeaderRowCellRendered,{node:y[0],column:a}))}Ca(V);ba();if(d.enableColumnReorder){var f=function(){K[0].scrollLeft+=10},g=function(){K[0].scrollLeft-=10};M.sortable();M.sortable("destroy");var v=null;M.sortable({containment:"parent",axis:"x",cursor:"default",tolerance:"intersection",helper:"clone",placeholder:"slick-sortable-placeholder ui-state-default slick-header-column",forcePlaceholderSize:!0,start:function(b,c){e(c.helper).addClass("slick-header-column-active")},
beforeStop:function(b,c){e(c.helper).removeClass("slick-header-column-active")},sort:function(b){b.originalEvent.pageX>D[0].clientWidth?v||(v=setInterval(f,100)):b.originalEvent.pageX<K.offset().left?v||(v=setInterval(g,100)):(clearInterval(v),v=null)},stop:function(b){clearInterval(v);v=null;if(B().commitCurrentEdit()){for(var c=Fa.sortable("toArray"),c=c.concat(Xa.sortable("toArray")),d=[],t=0;t<c.length;t++)d.push(h[$a(c[t].replace(aa,""))]);pb(d);j(n.onColumnsReordered,{});b.stopPropagation();
ba()}else e(this).sortable("cancel")}})}}function ba(){var b,c,t,a,l,y,f,g;a=M.children();a.find(".slick-resizable-handle").remove();a.each(function(b){h[b].resizable&&(void 0===f&&(f=b),g=b)});void 0!==f&&a.each(function(v,m){v<f||d.forceFitColumns&&v>=g||(e(m),e("<div class='slick-resizable-handle' />").appendTo(m).bind("dragstart",function(f){if(!B().commitCurrentEdit())return!1;t=f.pageX;e(this).parent().addClass("slick-header-column-active");var g=f=null;a.each(function(b,c){h[b].previousWidth=
e(c).outerWidth()});if(d.forceFitColumns){g=f=0;for(b=v+1;b<a.length;b++)c=h[b],c.resizable&&(null!==g&&(g=c.maxWidth?g+(c.maxWidth-c.previousWidth):null),f+=c.previousWidth-Math.max(c.minWidth||0,La))}var G=0,m=0;for(b=0;b<=v;b++)c=h[b],c.resizable&&(null!==m&&(m=c.maxWidth?m+(c.maxWidth-c.previousWidth):null),G+=c.previousWidth-Math.max(c.minWidth||0,La));null===f&&(f=1E5);null===G&&(G=1E5);null===g&&(g=1E5);null===m&&(m=1E5);y=t+Math.min(f,m);l=t-Math.min(G,g)}).bind("drag",function(e){var f=Math.min(y,
Math.max(l,e.pageX))-t,g;if(0>f){g=f;var G=0;for(b=v;0<=b;b--)c=h[b],c.resizable&&(e=Math.max(c.minWidth||0,La),g&&c.previousWidth+g<e?(g+=c.previousWidth-e,c.width=e):(c.width=c.previousWidth+g,g=0));for(k=0;k<=v;k++)c=h[k],-1<d.frozenColumn&&k>d.frozenColumn||(G+=c.width);if(d.forceFitColumns){g=-f;for(b=v+1;b<a.length;b++)c=h[b],c.resizable&&(g&&c.maxWidth&&c.maxWidth-c.previousWidth<g?(g-=c.maxWidth-c.previousWidth,c.width=c.maxWidth):(c.width=c.previousWidth+g,g=0),-1<d.frozenColumn&&b>d.frozenColumn||
(G+=c.width))}else for(b=v+1;b<a.length;b++)c=h[b],-1<d.frozenColumn&&b>d.frozenColumn||(G+=c.width)}else{g=f;G=0;for(b=v;0<=b;b--)c=h[b],c.resizable&&(g&&c.maxWidth&&c.maxWidth-c.previousWidth<g?(g-=c.maxWidth-c.previousWidth,c.width=c.maxWidth):(c.width=c.previousWidth+g,g=0));for(k=0;k<=v;k++)c=h[k],-1<d.frozenColumn&&k>d.frozenColumn||(G+=c.width);if(d.forceFitColumns){g=-f;for(b=v+1;b<a.length;b++)c=h[b],c.resizable&&(e=Math.max(c.minWidth||0,La),g&&c.previousWidth+g<e?(g+=c.previousWidth-e,
c.width=e):(c.width=c.previousWidth+g,g=0),-1<d.frozenColumn&&b>d.frozenColumn||(G+=c.width))}else for(b=v+1;b<a.length;b++)c=h[b],-1<d.frozenColumn&&b>d.frozenColumn||(G+=c.width)}-1<d.frozenColumn&&G!=E&&(Fa.width(G+1E3),mb.css("left",G));N();d.syncColumnCellResize&&(q(),Za())}).bind("dragend",function(){var d;e(this).parent().removeClass("slick-header-column-active");for(b=0;b<a.length;b++)c=h[b],d=e(a[b]).outerWidth(),c.previousWidth!==d&&c.rerenderOnResize&&ia();q(!0);H();j(n.onColumnsResized,
{})}))})}function x(b){var c=0;e.each(["borderTopWidth","borderBottomWidth","paddingTop","paddingBottom"],function(d,e){c+=parseFloat(b.css(e))||0});return c}function O(){d.frozenColumn=0<=d.frozenColumn&&d.frozenColumn<h.length?parseInt(d.frozenColumn):-1;d.frozenRow=0<=d.frozenRow&&d.frozenRow<Xb?parseInt(d.frozenRow):-1;if(-1<d.frozenRow){r=!0;ja=d.frozenRow*d.rowHeight;var b=u()||this.data.length;R=d.frozenBottom?b-d.frozenRow:d.frozenRow}}function T(){-1<d.frozenColumn?(mb.show(),Na.show(),r?
(ya.show(),Oa.show()):(Oa.hide(),ya.hide())):(mb.hide(),Na.hide(),Oa.hide(),r?ya.show():(Oa.hide(),ya.hide()))}function va(){U.css({"overflow-x":-1<d.frozenColumn?r?"hidden":"scroll":r?"hidden":"auto","overflow-y":-1<d.frozenColumn?"hidden":r?"scroll":"auto"});xa.css({"overflow-x":-1<d.frozenColumn?r?"hidden":"scroll":r?"hidden":"auto","overflow-y":r?"scroll":"auto"});fa.css({"overflow-x":-1<d.frozenColumn?r?"scroll":"auto":"auto","overflow-y":-1<d.frozenColumn?"hidden":r?"scroll":"auto"});Ia.css({"overflow-x":-1<
d.frozenColumn?r?"scroll":"auto":"auto","overflow-y":"auto"})}function oa(){-1<d.frozenColumn?(mc=Yb,Zb=Fb,r?d.frozenBottom?(K=Ia,ka=xa):K=ka=Ia:K=ka=xa):(mc=Gb,Zb=Ya,r?d.frozenBottom?(K=fa,ka=U):K=ka=fa:K=ka=U)}function Da(){ab=e("<style type='text/css' rel='stylesheet' />").appendTo(e("head"));for(var b=["."+aa+" .slick-header-column { left: 1000px; }","."+aa+" .slick-top-panel { height:"+d.topPanelHeight+"px; }","."+aa+" .slick-headerrow-columns { height:"+d.headerRowHeight+"px; }","."+aa+" .slick-cell { height:"+
(d.rowHeight-Sb)+"px; }","."+aa+" .slick-row { height:"+d.rowHeight+"px; }"],c=0;c<h.length;c++)b.push("."+aa+" .l"+c+" { }"),b.push("."+aa+" .r"+c+" { }");ab[0].styleSheet?ab[0].styleSheet.cssText=b.join(" "):ab[0].appendChild(document.createTextNode(b.join(" ")))}function j(b,c,d){d=d||new Slick.EventData;c=c||{};c.grid=n;return b.notify(c,d,n)}function B(){return d.editorLock}function $a(b){return ga[b]}function Pa(){var b,c,d=[],e=0,a=0,l,f=jb?W-g.width:W;for(b=0;b<h.length;b++)c=h[b],d.push(c.width),
a+=c.width,c.resizable&&(e+=c.width-Math.max(c.minWidth,La));for(l=a;a>f&&e;){var y=(a-f)/e;for(b=0;b<h.length&&a>f;b++){c=h[b];var v=d[b];if(c.resizable&&!(v<=c.minWidth||v<=La)){c=Math.max(c.minWidth,La);var m=Math.floor(y*(v-c))||1,m=Math.min(m,v-c),a=a-m,e=e-m;d[b]-=m}}if(l==a)break;l=a}for(l=a;a<f;){e=f/a;for(b=0;b<h.length&&a<f;b++)c=h[b],c.resizable&&!(c.maxWidth<=c.width)&&(y=Math.min(Math.floor(e*c.width)-c.width,c.maxWidth-c.width||1E6)||1,a+=y,d[b]+=y);if(l==a)break;l=a}a=!1;for(b=0;b<
h.length;b++)h[b].rerenderOnResize&&h[b].width!=d[b]&&(a=!0),h[b].width=d[b];N();q(!0);a&&(ia(),H())}function N(){if(ua){for(var b,c=0,d=M.children(),a=d.length;c<a;c++)b=e(d[c]),b.width()!==h[c].width-Ua&&b.width(h[c].width-Ua);gb()}}function Za(){for(var b,c,a=0,e,l=0;l<h.length;l++){e=h[l].width;c=l;if(!bb){var g=document.styleSheets;for(b=0;b<g.length;b++)if((g[b].ownerNode||g[b].owningElement)==ab[0]){bb=g[b];break}if(!bb)throw Error("Cannot find stylesheet.");nc=[];oc=[];var g=bb.cssRules||
bb.rules,f=void 0,f=void 0;for(b=0;b<g.length;b++){var y=g[b].selectorText;if(f=/\.l\d+/.exec(y))f=parseInt(f[0].substr(2,f[0].length-2),10),nc[f]=g[b];else if(f=/\.r\d+/.exec(y))f=parseInt(f[0].substr(2,f[0].length-2),10),oc[f]=g[b]}}b=nc[c];c=oc[c];b.style.left=a+"px";c.style.right=(-1!=d.frozenColumn&&l>d.frozenColumn?qa:E)-a-e+"px";a=d.frozenColumn==l?0:a+h[l].width}}function Ca(b){V=b;var c=M.children();c.removeClass("slick-header-column-sorted").find(".slick-sort-indicator").removeClass("slick-sort-indicator-asc slick-sort-indicator-desc");
e.each(V,function(b,d){null==d.sortAsc&&(d.sortAsc=!0);var a=ga[d.columnId];null!=a&&c.eq(a).addClass("slick-header-column-sorted").find(".slick-sort-indicator").addClass(d.sortAsc?"slick-sort-indicator-asc":"slick-sort-indicator-desc")})}function X(b,c){pc=[];for(var a={},e=0;e<c.length;e++)for(var l=c[e].fromRow;l<=c[e].toRow;l++){a[l]||(pc.push(l),a[l]={});for(var g=c[e].fromCell;g<=c[e].toCell;g++)Jc(l,g)&&(a[l][h[g].id]=d.selectedCellCssClass)}Kc(d.selectedCellCssClass,a);j(n.onSelectedRowsChanged,
{rows:Lc()},b)}function gb(){qb=[];rb=[];for(var b=0,c=0,a=h.length;c<a;c++)qb[c]=b,rb[c]=b+h[c].width,b=d.frozenColumn==c?0:b+h[c].width}function pb(b){h=b;ga={};for(b=0;b<h.length;b++){var c=h[b]=e.extend({},qc,h[b]);ga[c.id]=b;c.minWidth&&c.width<c.minWidth&&(c.width=c.minWidth);c.maxWidth&&c.width>c.maxWidth&&(c.width=c.maxWidth)}gb();ua&&(T(),va(),ia(),Wa(),ab.remove(),bb=null,Da(),$(),q(),Za(),Eb())}function u(){return m.getLength?m.getLength():m.length}function L(b){return m.getItem?m.getItem(b):
m[b]}function la(b){b=Math.max(b,0);b=Math.min(b,za-ka.height()+(lc||-1<d.frozenColumn?g.height:0));var c=I;sb=Math.min(tb-1,Math.floor(b/ub));I=Math.round(sb*$b);b-=I;if(I!=c){var a=y(b);Aa(a);for(var e in C)C[e].rowNode.css("top",e*d.rowHeight-I+"px")}vb!=b&&(cb=vb+c<b+I?1:-1,ac=F=vb=b,-1<d.frozenColumn&&(U[0].scrollTop=b),r&&(fa[0].scrollTop=Ia[0].scrollTop=b),ka[0].scrollTop=b,j(n.onViewportChanged,{}))}function Qa(b,c){var a=m.getItemMetadata&&m.getItemMetadata(b),e=a&&a.columns&&(a.columns[c.id]||
a.columns[ga[c.id]]);return e&&e.formatter||a&&a.formatter||c.formatter||d.formatterFactory&&d.formatterFactory.getFormatter(c)||d.defaultFormatter}function Hb(b,c){var a=h[c],e=m.getItemMetadata&&m.getItemMetadata(b);return(e=e&&e.columns)&&e[a.id]&&void 0!==e[a.id].editor?e[a.id].editor:e&&e[c]&&void 0!==e[c].editor?e[c].editor:a.editor||d.editorFactory&&d.editorFactory.getEditor(a)}function Y(b,c){return d.dataItemColumnValueExtractor?d.dataItemColumnValueExtractor(b,c):b[c.field]}function Ja(b,
c,d,a){var e=h[d],l=L(c),g="slick-cell l"+d+" r"+Math.min(h.length-1,d+a-1)+(e.cssClass?" "+e.cssClass:"");c===s&&d===z&&(g+=" active");for(var f in ma)ma[f][c]&&ma[f][c][e.id]&&(g+=" "+ma[f][c][e.id]);b.push("<div class='"+g+"'>");l&&(g=Y(l,e),b.push(Qa(c,e)(c,d,g,e,l)));b.push("</div>");C[c].cellRenderQueue.push(d);C[c].cellColSpans[d]=a}function Aa(b){for(var c in C){var a=!1;if(r&&(d.frozenBottom&&c<R||c>=R))a=!0;(c=parseInt(c,10))!==s&&((c<b.top||c>b.bottom)&&a)&&Ra(c)}}function ia(){p&&Ka();
for(var b in C)Ra(b)}function Ra(b){var c=C[b];c&&(c.rowNode[0].parentElement.removeChild(c.rowNode[0]),c.rowNode[1]&&c.rowNode[1].parentElement.removeChild(c.rowNode[1]),delete C[b],delete Sa[b],rc--,Mc++)}function J(b){var c,d;if(b&&b.length){c=cb=0;for(d=b.length;c<d;c++)p&&s===b[c]&&Ka(),C[b[c]]&&Ra(b[c])}}function ca(b){J([b])}function da(b){var c=C[b];if(c){P(b);for(var d in c.cellNodesByColumnIdx)if(c.cellNodesByColumnIdx.hasOwnProperty(d)){d|=0;var a=h[d],e=L(b),l=c.cellNodesByColumnIdx[d][0];
b===s&&d===z&&p?p.loadValue(e):l.innerHTML=e?Qa(b,a)(b,d,Y(e,a),a,e):""}A(b)}}function Db(){na=d.autoHeight?d.rowHeight*(u()+(d.enableAddRow?1:0))+(-1==d.frozenColumn?M.outerHeight():0):parseFloat(e.css(D[0],"height",!0))-parseFloat(e.css(D[0],"paddingTop",!0))-parseFloat(e.css(D[0],"paddingBottom",!0))-parseFloat(e.css(Ub[0],"height"))-x(Ub)-(d.showTopPanel?d.topPanelHeight+x(db):0);Xb=Math.ceil(na/d.rowHeight)}function Cb(){W=parseFloat(e.css(D[0],"width",!0))}function $(){if(ua){wb=Ta=ea=0;var b=
d.showTopPanel?db.outerHeight():0,c=d.showHeaderRow?Ya.outerHeight():0;Cb();Db();r?d.frozenBottom?(ea=na-ja-g.height,Ta=ja+g.height):(ea=ja,Ta=na-ja-b-c):ea=na;ea+=b+c;-1<d.frozenColumn&&d.autoHeight&&(ea+=g.height);wb=ea-b-c;d.autoHeight&&(-1<d.frozenColumn&&D.height(ea+parseFloat(e.css(Gb[0],"height"))),Ga.css("position","relative"));Ga.css({top:lb.height(),height:ea});b=Ga.position().top+ea;U.height(wb);-1<d.frozenColumn?(Na.css({top:lb.height(),height:ea}),xa.height(wb),r&&(ya.css({top:b,height:Ta}),
Oa.css({top:b,height:Ta}),Ia.height(Ta))):r&&(ya.css({width:"100%",height:Ta}),ya.css("top",b));r?(fa.height(Ta),d.frozenBottom?(wa.height(ja),-1<d.frozenColumn&&ob.height(ja)):(pa.height(ja),-1<d.frozenColumn&&kb.height(ja))):xa.height(wb);d.forceFitColumns&&Pa();l();Eb();H()}}function l(){if(ua){var b=r&&!d.frozenBottom?wa.height():pa.height();sc=r&&d.frozenBottom?u()-d.frozenRow:u()+(d.enableAddRow?1:0)+(d.leaveSpaceForNewRows?Xb-1:0);var c=ka.height(),e=jb;jb=!d.autoHeight&&sc*d.rowHeight>c;var l=
d.enableAddRow?u():u()-1,f;for(f in C)f>=l&&Ra(f);za=Math.max(d.rowHeight*sc,c-g.height);w&&s>l&&Nc();za<a?(Z=ub=za,tb=1,$b=0):(Z=a,ub=Z/100,tb=Math.floor(za/ub),$b=(za-Z)/(tb-1));Z!==b&&(r&&!d.frozenBottom?(wa.css("height",Z),-1<d.frozenColumn&&ob.css("height",Z)):(pa.css("height",Z),kb.css("height",Z)),F=ka[0].scrollTop);l=F+I<=za-c;0==za||0==F?sb=I=0:l?la(F+I):la(za-c);Z!=b&&d.autoHeight&&$();d.forceFitColumns&&e!=jb&&Pa();q(!1)}}function y(b,c){null==b&&(b=F);null==c&&(c=Q);return{top:Math.floor((b+
I)/d.rowHeight),bottom:Math.ceil((b+I+na)/d.rowHeight),leftPx:c,rightPx:c+W}}function v(b,c){var a=y(b,c),e=Math.round(na/d.rowHeight);-1==cb?(a.top-=e,a.bottom+=3):1==cb?(a.top-=3,a.bottom+=e):(a.top-=3,a.bottom+=3);a.top=Math.max(0,a.top);a.bottom=Math.min(d.enableAddRow?u():u()-1,a.bottom);a.leftPx-=W;a.rightPx+=W;a.leftPx=Math.max(0,a.leftPx);a.rightPx=Math.min(xd,a.rightPx);return a}function P(b){if((b=C[b])&&b.cellRenderQueue.length)for(var c=b.rowNode.children().last();b.cellRenderQueue.length;){var a=
b.cellRenderQueue.pop();b.cellNodesByColumnIdx[a]=c;c=c.prev();0==c.length&&(c=e(b.rowNode[0]).children().last())}}function S(b){for(var c=[],a=[],l=[],g=!1,f=b.top;f<=b.bottom;f++)if(!(C[f]||r&&d.frozenBottom&&f==u())){rc++;l.push(f);C[f]={rowNode:null,cellColSpans:[],cellNodesByColumnIdx:[],cellRenderQueue:[]};var y=c,v=a,P=f,Ib=b,n=L(P),j="slick-row"+(P<u()&&!n?" loading":"")+(P===s?" active":"")+(1==P%2?" odd":" even");(n=m.getItemMetadata&&m.getItemMetadata(P))&&n.cssClasses&&(j+=" "+n.cssClasses);
j="<div class='ui-widget-content "+j+"' style='top:"+(d.rowHeight*P-I-(r?d.frozenBottom?P>=R?Z<wb?R*d.rowHeight:Z:0:P>=R?ja:0:0))+"px'>";y.push(j);-1<d.frozenColumn&&v.push(j);for(var S=void 0,p=void 0,j=0,A=h.length;j<A;j++){p=h[j];S=1;n&&n.columns&&(S=(S=n.columns[p.id]||n.columns[j])&&S.colspan||1,"*"===S&&(S=A-j));if(rb[Math.min(A-1,j+S-1)]>Ib.leftPx){if(qb[j]>Ib.rightPx)break;-1<d.frozenColumn&&j>d.frozenColumn?Ja(v,P,j,S):Ja(y,P,j,S)}else-1<d.frozenColumn&&j<=d.frozenColumn&&Ja(y,P,j,S);1<S&&
(j+=S-1)}y.push("</div>");-1<d.frozenColumn&&v.push("</div>");w&&s===f&&(g=!0);Oc++}if(l.length){b=document.createElement("div");y=document.createElement("div");b.innerHTML=c.join("");y.innerHTML=a.join("");f=0;for(c=l.length;f<c;f++)C[l[f]].rowNode=r&&l[f]>=R?-1<d.frozenColumn?e().add(e(b.firstChild).appendTo(wa)).add(e(y.firstChild).appendTo(ob)):e().add(e(b.firstChild).appendTo(wa)):-1<d.frozenColumn?e().add(e(b.firstChild).appendTo(pa)).add(e(y.firstChild).appendTo(kb)):e().add(e(b.firstChild).appendTo(pa));
g&&(w=ra(s,z))}}function Ib(){d.enableAsyncPostRender&&(clearTimeout(tc),tc=setTimeout(Pc,d.asyncPostRenderDelay))}function A(b){delete Sa[b];xb=Math.min(xb,b);Jb=Math.max(Jb,b);Ib()}function H(){if(ua){var b=y(),c=v();Aa(c);if(bc!=Q){for(var a,l=[],g=[],f,j,n=c.top;n<=c.bottom;n++)if(a=C[n]){P(n);j=c;f=n;if(!r||!(d.frozenBottom&&f>R||f<=R)){var p=0,A=C[f],H=[],q=void 0;for(q in A.cellNodesByColumnIdx)if(A.cellNodesByColumnIdx.hasOwnProperty(q)&&(q|=0,!(q<=d.frozenColumn))){var w=A.cellColSpans[q];
if(qb[q]>j.rightPx||rb[Math.min(h.length-1,q+w-1)]<j.leftPx)f==s&&q==z||H.push(q)}for(j=void 0;null!=(j=H.pop());)A.cellNodesByColumnIdx[j][0].parentElement.removeChild(A.cellNodesByColumnIdx[j][0]),delete A.cellColSpans[j],delete A.cellNodesByColumnIdx[j],Sa[f]&&delete Sa[f][j],p++}f=0;p=(p=m.getItemMetadata&&m.getItemMetadata(n))&&p.columns;A=0;for(H=h.length;A<H&&!(qb[A]>c.rightPx);A++){if(null==(j=a.cellColSpans[A]))j=1,p&&(j=(j=p[h[A].id]||p[A])&&j.colspan||1,"*"===j&&(j=H-A)),rb[Math.min(H-
1,A+j-1)]>c.leftPx&&(Ja(l,n,A,j),f++);A+=1<j?j-1:0}f&&g.push(n)}if(l.length){n=document.createElement("div");for(n.innerHTML=l.join("");null!=(a=g.pop());)for(a=C[a];null!=(f=a.cellRenderQueue.pop());)l=e(n).children().last(),-1<d.frozenColumn&&f>d.frozenColumn?e(a.rowNode[1]).append(l):e(a.rowNode[0]).append(l),a.cellNodesByColumnIdx[f]=l}}S(c);d.frozenBottom&&S({top:R,bottom:u()-1,leftPx:c.leftPx,rightPx:c.rightPx});xb=b.top;Jb=Math.min(d.enableAddRow?u():u()-1,b.bottom);Ib();ac=F;bc=Q;cc=null}}
function nd(){var b=Zb[0].scrollLeft;b!=K[0].scrollLeft&&(K[0].scrollLeft=b)}function Eb(){F=ka[0].scrollTop;Q=K[0].scrollLeft;var b=Math.abs(F-vb),c=Math.abs(Q-Qc);c&&(Qc=Q,mc[0].scrollLeft=Q,db[0].scrollLeft=Q,Zb[0].scrollLeft=Q,-1<d.frozenColumn?r&&(xa[0].scrollLeft=Q):r&&(U[0].scrollLeft=Q));if(b)if(cb=vb<F?1:-1,vb=F,-1<d.frozenColumn&&(r&&!d.frozenBottom?fa[0].scrollTop=F:U[0].scrollTop=F),b<na)la(F+I);else{var a=I;sb=Z==na?0:Math.min(tb-1,Math.floor(F*((za-na)/(Z-na))*(1/ub)));I=Math.round(sb*
$b);a!=I&&ia()}if(c||b)if(cc&&clearTimeout(cc),20<Math.abs(ac-F)||20<Math.abs(bc-Q))d.forceSyncScrolling||Math.abs(ac-F)<na&&Math.abs(bc-Q)<W?H():cc=setTimeout(H,50),j(n.onViewportChanged,{});j(n.onScroll,{scrollLeft:Q,scrollTop:F})}function Fc(b,c){0<c?la(F-Math.abs(c)*d.rowHeight):la(F+Math.abs(c)*d.rowHeight);H();b.preventDefault();j(n.onMouseWheel,{scrollTop:F})}function Pc(){for(;xb<=Jb;){var b=0<=cb?xb++:Jb--,c=C[b];if(c&&!(b>=u())){Sa[b]||(Sa[b]={});P(b);for(var a in c.cellNodesByColumnIdx)if(c.cellNodesByColumnIdx.hasOwnProperty(a)){a|=
0;var e=h[a];if(e.asyncPostRender&&!Sa[b][a]){var l=c.cellNodesByColumnIdx[a];l&&e.asyncPostRender(l,xb,L(b),e);Sa[b][a]=!0}}tc=setTimeout(Pc,d.asyncPostRenderDelay);break}}}function uc(b,c){var a,d,l,f,g;for(g in C){f=c&&c[g];l=b&&b[g];if(f)for(d in f)if(!l||f[d]!=l[d])(a=ra(g,ga[d]))&&e(a).removeClass(f[d]);if(l)for(d in l)if(!f||f[d]!=l[d])(a=ra(g,ga[d]))&&e(a).addClass(l[d])}}function Kc(b,c){var a=ma[b];ma[b]=c;uc(c,a);j(n.onCellCssStylesChanged,{key:b,hash:c})}function rd(b,c){var a=Kb(b);if(!a||
!vc(a.row,a.cell))return!1;retval=j(n.onDragInit,c,b);return b.isImmediatePropagationStopped()?retval:!1}function sd(b,c){var a=Kb(b);if(!a||!vc(a.row,a.cell))return!1;a=j(n.onDragStart,c,b);return b.isImmediatePropagationStopped()?a:!1}function td(b,c){return j(n.onDrag,c,b)}function ud(b,c){j(n.onDragEnd,c,b)}function Hc(b){j(n.onKeyDown,{row:s,cell:z},b);var c=b.isImmediatePropagationStopped();if(!c)if(!b.shiftKey&&!b.altKey&&!b.ctrlKey)if(27==b.which){if(!B().isActive())return;Rc()}else 37==b.which?
c=Sc():39==b.which?c=Tc():38==b.which?c=Uc():40==b.which?c=dc():9==b.which?c=Vc():13==b.which&&(d.editable&&(p?s===u()?dc():Wc():B().commitCurrentEdit()&&ec()),c=!0);else 9==b.which&&(b.shiftKey&&!b.ctrlKey&&!b.altKey)&&(c=Xc());if(c){b.stopPropagation();b.preventDefault();try{b.originalEvent.keyCode=0}catch(a){}}}function od(b){p||b.target!=document.activeElement&&eb();var c=Kb(b);if(c&&!(null!==p&&s==c.row&&z==c.cell)&&(j(n.onClick,{row:c.row,cell:c.cell},b),!b.isImmediatePropagationStopped()&&
(z!=c.cell||s!=c.row)&&Ba(c.row,c.cell)))if(!B().isActive()||B().commitCurrentEdit())r&&(!d.frozenBottom&&c.row>=R||d.frozenBottom&&c.row<R)&&Lb(c.row,!1),yb(ra(c.row,c.cell),c.row===u()||d.autoEdit)}function qd(b){var c=e(b.target).closest(".slick-cell",Va);0!==c.length&&(w===c[0]&&null!==p||j(n.onContextMenu,{},b))}function pd(b){var c=Kb(b);c&&!(null!==p&&s==c.row&&z==c.cell)&&(j(n.onDblClick,{row:c.row,cell:c.cell},b),b.isImmediatePropagationStopped()||d.editable&&Yc(c.row,c.cell,!0))}function ld(b){j(n.onHeaderMouseEnter,
{column:e(this).data("column")},b)}function md(b){j(n.onHeaderMouseLeave,{column:e(this).data("column")},b)}function jd(b){var c=e(b.target).closest(".slick-header-column",".slick-header-columns"),c=c&&c.data("column");j(n.onHeaderContextMenu,{column:c},b)}function kd(b){var c=e(b.target).closest(".slick-header-column",".slick-header-columns");(c=c&&c.data("column"))&&j(n.onHeaderClick,{column:c},b)}function vd(b){j(n.onMouseEnter,{},b)}function wd(b){j(n.onMouseLeave,{},b)}function vc(b,c){return!(0>
b||b>=u()||0>c||c>=h.length)}function wc(b,c){for(var a=Math.floor((c+I)/d.rowHeight),e=0,l=0,f=0;f<h.length&&l<b;f++)l+=h[f].width,e++;0>e&&(e=0);return{row:a,cell:e-1}}function Zc(b){var c=/l\d+/.exec(b.className);if(!c)throw"getCellFromNode: cannot get cell - "+b.className;return parseInt(c[0].substr(1,c[0].length-1),10)}function Kb(b){var c=e(b.target).closest(".slick-cell",Va);if(!c.length)return null;var a=c.parents(".grid-canvas").offset(),l=0,f=c.parents(".grid-canvas-bottom").length;r&&f&&
(l=d.frozenBottom?pa.height():ja);b=wc(b.clientX-a.left,b.clientY-a.top+l+e(document).scrollTop()).row;c=Zc(c[0]);return null==b||null==c?null:{row:b,cell:c}}function Nc(){yb(null,!1)}function eb(){-1==$c?Vb[0].focus():kc[0].focus()}function Mb(b,c){if(!(c<=d.frozenColumn)){var a=zb(b,c),e=qb[c],a=rb[c+(1<a?a-1:0)],l=Q+K.width();e<Q?(K.scrollLeft(e),Eb(),H()):a>l&&(K.scrollLeft(Math.min(e,a-K[0].clientWidth)),Eb(),H())}}function yb(b,c){null!==w&&(Ka(),e(w).removeClass("active"),C[s]&&e(C[s].rowNode).removeClass("active"));
var a=w!==b;w=b;if(null!=w){var l=e(w),f=l.offset(),g=Math.floor(l.parents(".grid-canvas").offset().top),h=l.parents(".grid-canvas-bottom").length;r&&h&&(g-=d.frozenBottom?pa.height():ja);cell=wc(f.left,Math.ceil(f.top)-g);s=cell.row;z=fc=z=fc=Zc(w[0]);l.addClass("active");d.editable&&(c&&ad(s,z))&&(clearTimeout(xc),d.asyncEditorLoading?xc=setTimeout(function(){ec()},d.asyncEditorLoadDelay):ec())}else s=z=null;a&&(setTimeout(yd,50),j(n.onActiveCellChanged,bd()))}function ad(b,c){return b<u()&&!L(b)||
h[c].cannotTriggerInsert&&b>=u()||!Hb(b,c)?!1:!0}function Ka(){if(p){j(n.onBeforeCellEditorDestroy,{editor:p});p.destroy();p=null;if(w){var b=L(s);e(w).removeClass("editable invalid");if(b){var c=h[z],a=Qa(s,c);w[0].innerHTML=a(s,z,Y(b,c),c,L(s));A(s)}}e.browser.msie&&(document.selection&&document.selection.empty?document.selection.empty():window.getSelection&&(b=window.getSelection())&&b.removeAllRanges&&b.removeAllRanges());B().deactivate(gc)}}function ec(b){if(w){if(!d.editable)throw"Grid : makeActiveCellEditable : should never get called when options.editable is false";
clearTimeout(xc);if(ad(s,z)){var c=h[z],a=L(s);!1===j(n.onBeforeEditCell,{row:s,cell:z,item:a,column:c})?eb():(B().activate(gc),e(w).addClass("editable"),b||(w[0].innerHTML=""),p=new (b||Hb(s,z))({grid:n,gridPosition:hc(D[0]),position:hc(w[0]),container:w,column:c,item:a||{},commitChanges:Wc,cancelChanges:Rc}),a&&p.loadValue(a),cd=p.serializeValue(),p.position&&Gc())}}}function Wc(){B().commitCurrentEdit()&&(eb(),d.autoEdit&&dc())}function Rc(){B().cancelCurrentEdit()&&eb()}function hc(b){var c={top:b.offsetTop,
left:b.offsetLeft,bottom:0,right:0,width:e(b).outerWidth(),height:e(b).outerHeight(),visible:!0};c.bottom=c.top+c.height;c.right=c.left+c.width;for(var a=b.offsetParent;(b=b.parentNode)!=document.body;)c.visible&&(b.scrollHeight!=b.offsetHeight&&"visible"!=e(b).css("overflowY"))&&(c.visible=c.bottom>b.scrollTop&&c.top<b.scrollTop+b.clientHeight),c.visible&&(b.scrollWidth!=b.offsetWidth&&"visible"!=e(b).css("overflowX"))&&(c.visible=c.right>b.scrollLeft&&c.left<b.scrollLeft+b.clientWidth),c.left-=
b.scrollLeft,c.top-=b.scrollTop,b===a&&(c.left+=b.offsetLeft,c.top+=b.offsetTop,a=b.offsetParent),c.bottom=c.top+c.height,c.right=c.left+c.width;return c}function dd(){return hc(w[0])}function Gc(){if(w&&(j(n.onActiveCellPositionChanged,{}),p)){var b=dd();p.show&&p.hide&&(b.visible?p.show():p.hide());p.position&&p.position(b)}}function bd(){return w?{row:s,cell:z}:null}function yd(){null!=s&&null!=z&&Mb(s,z)}function Lb(b,c){r&&!d.frozenBottom&&(b-=R);var a=ka.height(),e=b*d.rowHeight,l=(b+1)*d.rowHeight-
a+(lc?g.height:0);(b+1)*d.rowHeight>F+a+I?(la(c?e:l),H()):b*d.rowHeight<F+I&&(la(c?l:e),H())}function zb(b,c){var a=m.getItemMetadata&&m.getItemMetadata(b);if(!a||!a.columns)return 1;a=(a=a.columns[h[c].id]||a.columns[c])&&a.colspan;return(a="*"===a?h.length-c:a||1)||1}function ed(b){for(var c=0;c<h.length;){if(Ba(b,c))return c;c+=zb(b,c)}return null}function yc(b,c){if(c>=h.length)return null;do c+=zb(b,c);while(c<h.length&&!Ba(b,c));return c<h.length?{row:b,cell:c,posX:c}:null}function fd(b,c){if(0>=
c)return null;var a=ed(b);if(null===a||a>=c)return null;for(var a={row:b,cell:a,posX:a},d;;){d=yc(a.row,a.cell,a.posX);if(!d)return null;if(d.cell>=c)return a;a=d}}function zd(b,c,a){for(var e;;){if(++b>=u()+(d.enableAddRow?1:0))return null;for(e=c=0;c<=a;)e=c,c+=zb(b,c);if(Ba(b,e))return{row:b,cell:e,posX:a}}}function Ad(b,c,a){for(var d;;){if(0>--b)return null;for(d=c=0;c<=a;)d=c,c+=zb(b,c);if(Ba(b,d))return{row:b,cell:d,posX:a}}}function Bd(b,c,a){if(null==b&&null==c&&(b=c=a=0,Ba(b,c)))return{row:b,
cell:c,posX:c};if(c=yc(b,c,a))return c;for(c=null;++b<u()+(d.enableAddRow?1:0);)if(c=ed(b),null!==c)return{row:b,cell:c,posX:c};return null}function Cd(b,c,a){if(null==b&&null==c&&(b=u()+(d.enableAddRow?1:0)-1,c=a=h.length-1,Ba(b,c)))return{row:b,cell:c,posX:c};for(var e,l;!e&&!(e=fd(b,c,a));){if(0>--b)return null;c=0;l=b;for(var f=0,g=null;f<h.length;)Ba(l,f)&&(g=f),f+=zb(l,f);l=g;null!==l&&(e={row:b,cell:l,posX:l})}return e}function Tc(){return Ab("right")}function Sc(){return Ab("left")}function dc(){return Ab("down")}
function Uc(){return Ab("up")}function Vc(){return Ab("next")}function Xc(){return Ab("prev")}function Ab(b){if(!d.enableCellNavigation||!w&&"prev"!=b&&"next"!=b)return!1;if(!B().commitCurrentEdit())return!0;eb();$c={up:-1,down:1,left:-1,right:1,prev:-1,next:1}[b];if(b=(0,{up:Ad,down:zd,left:fd,right:yc,prev:Cd,next:Bd}[b])(s,z,fc)){if(!(r&&d.frozenBottom&b.row==u())){var c=b.row==u();(!d.frozenBottom&&b.row>=R||d.frozenBottom&&b.row<R)&&Lb(b.row,!c);Mb(b.row,b.cell);yb(ra(b.row,b.cell),c||d.autoEdit);
fc=b.posX;return!0}}else return yb(ra(s,z),s==u()||d.autoEdit),!1}function ra(b,c){return C[b]?(P(b),C[b].cellNodesByColumnIdx[c]):null}function Ba(b,c){if(!d.enableCellNavigation||b>=u()+(d.enableAddRow?1:0)||0>b||c>=h.length||0>c)return!1;var a=m.getItemMetadata&&m.getItemMetadata(b);return a&&"boolean"===typeof a.focusable?a.focusable:(a=a&&a.columns)&&a[h[c].id]&&"boolean"===typeof a[h[c].id].focusable?a[h[c].id].focusable:a&&a[c]&&"boolean"===typeof a[c].focusable?a[c].focusable:"boolean"===
typeof h[c].focusable?h[c].focusable:!0}function Jc(b,c){if(b>=u()||0>b||c>=h.length||0>c)return!1;var a=m.getItemMetadata&&m.getItemMetadata(b);return a&&"boolean"===typeof a.selectable?a.selectable:(a=a&&a.columns&&(a.columns[h[c].id]||a.columns[c]))&&"boolean"===typeof a.selectable?a.selectable:"boolean"===typeof h[c].selectable?h[c].selectable:!0}function Yc(b,c,a){ua&&(Ba(b,c)&&B().commitCurrentEdit())&&(Lb(b,!1),Mb(b,c),c=ra(b,c),yb(c,a||b===u()||d.autoEdit),p||eb())}function Dd(b){for(var c=
[],a=h.length-1,d=0;d<b.length;d++)c.push(new Slick.Range(b[d],0,b[d],a));return c}function Lc(){if(!sa)throw"Selection model is not set";return pc}var Ed={explicitInitialization:!1,rowHeight:25,defaultColumnWidth:80,enableAddRow:!1,leaveSpaceForNewRows:!1,editable:!1,autoEdit:!0,enableCellNavigation:!0,enableColumnReorder:!0,asyncEditorLoading:!1,asyncEditorLoadDelay:100,forceFitColumns:!1,enableAsyncPostRender:!1,asyncPostRenderDelay:50,autoHeight:!1,editorLock:Slick.GlobalEditorLock,showHeaderRow:!1,
headerRowHeight:25,showTopPanel:!1,topPanelHeight:25,formatterFactory:null,editorFactory:null,cellFlashingCssClass:"flashing",selectedCellCssClass:"selected",multiSelect:!0,enableTextSelectionOnCells:!1,dataItemColumnValueExtractor:null,frozenBottom:!1,frozenColumn:-1,frozenRow:-1,fullWidthRows:!1,multiColumnSort:!1,defaultFormatter:function(b,c,a){return null==a?"":a.toString().replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},forceSyncScrolling:!1},qc={name:"",resizable:!0,sortable:!1,
minWidth:30,rerenderOnResize:!1,headerCssClass:null,defaultSortAsc:!0},za,Z,ub,tb,$b,sb=0,I=0,cb=1,ua=!1,D,aa="slickgrid_"+Math.round(1E6*Math.random()),n=this,Vb,kc,Ub,M,Wb,ib,Ic,db,gd,Tb,Va,ab,hb,bb,nc,oc,na,W,xd,E,qa,ha,Ea,lc,jb,Ua=0,jc=0,Rb=0,Sb=0,La,sc=0,r=!1,ja=0,R=-1,ea=0,Ta=0,wb=0,$c=1,fc,s,z,w=null,p=null,cd,gc,C={},rc=0,Xb=0,vb=0,F=0,ac=0,bc=0,Qc=0,Q=0,sa,pc=[],Ma=[],ma={},ga={},V=[],qb=[],rb=[],xc=null,cc=null,tc=null,Sa={},Jb=null,xb=null,Oc=0,Mc=0,lb,mb,Ga,Na,ya,Oa,Gb,Yb,Fa,Xa,Ya,Fb,
Ha,nb,zc,Ac,hd,id,U,xa,fa,Ia,pa,kb,wa,ob,K,ka,mc,Zb;this.debug=function(){var b;b="\ncounter_rows_rendered:  "+Oc;b+="\ncounter_rows_removed:  "+Mc;b+="\nrenderedRows:  "+rc;b+="\nnumVisibleRows:  "+Xb;b+="\nmaxSupportedCssHeight:  "+a;b+="\nn(umber of pages):  "+tb;b+="\n(current) page:  "+sb;b+="\npage height (ph):  "+ub;b+="\nvScrollDir:  "+cb;alert(b)};this.eval=function(b){return eval(b)};e.extend(this,{slickGridVersion:"2.1",onScroll:new Slick.Event,onMouseWheel:new Slick.Event,onSort:new Slick.Event,
onHeaderMouseEnter:new Slick.Event,onHeaderMouseLeave:new Slick.Event,onHeaderContextMenu:new Slick.Event,onHeaderClick:new Slick.Event,onHeaderCellRendered:new Slick.Event,onBeforeHeaderCellDestroy:new Slick.Event,onHeaderRowCellRendered:new Slick.Event,onBeforeHeaderRowCellDestroy:new Slick.Event,onMouseEnter:new Slick.Event,onMouseLeave:new Slick.Event,onClick:new Slick.Event,onDblClick:new Slick.Event,onContextMenu:new Slick.Event,onKeyDown:new Slick.Event,onAddNewRow:new Slick.Event,onValidationError:new Slick.Event,
onViewportChanged:new Slick.Event,onColumnsReordered:new Slick.Event,onColumnsResized:new Slick.Event,onCellChange:new Slick.Event,onBeforeEditCell:new Slick.Event,onBeforeCellEditorDestroy:new Slick.Event,onBeforeDestroy:new Slick.Event,onActiveCellChanged:new Slick.Event,onActiveCellPositionChanged:new Slick.Event,onDragInit:new Slick.Event,onDragStart:new Slick.Event,onDrag:new Slick.Event,onDragEnd:new Slick.Event,onSelectedRowsChanged:new Slick.Event,onCellCssStylesChanged:new Slick.Event,registerPlugin:function(b){Ma.unshift(b);
b.init(n)},unregisterPlugin:Pb,getColumns:function(){return h},setColumns:pb,getColumnIndex:$a,updateColumnHeader:function(b,c,a){if(ua&&(b=ga[b],null!=b)){var d=h[b],e=M.children().eq(b);e&&(void 0!==c&&(h[b].name=c),void 0!==a&&(h[b].toolTip=a),j(n.onBeforeHeaderCellDestroy,{node:e[0],column:d}),e.attr("title",a||"").children().eq(0).html(c),j(n.onHeaderCellRendered,{node:e[0],column:d}))}},setSortColumn:function(b,c){Ca([{columnId:b,sortAsc:c}])},setSortColumns:Ca,getSortColumns:function(){return V},
autosizeColumns:Pa,getOptions:function(){return d},setOptions:function(b){B().commitCurrentEdit()&&(Ka(),d.enableAddRow!==b.enableAddRow&&ca(u()),d=e.extend(d,b),d.autoHeight&&(d.leaveSpaceForNewRows=!1),O(),oa(),pb(h),H())},getData:function(){return m},getDataLength:u,getDataItem:L,setData:function(b,c){m=b;ia();l();c&&la(0)},getSelectionModel:function(){return sa},setSelectionModel:function(b){sa&&(sa.onSelectedRangesChanged.unsubscribe(X),sa.destroy&&sa.destroy());if(sa=b)sa.init(n),sa.onSelectedRangesChanged.subscribe(X)},
getSelectedRows:Lc,setSelectedRows:function(b){if(!sa)throw"Selection model is not set";sa.setSelectedRanges(Dd(b))},render:H,invalidate:function(){l();ia();H()},invalidateRow:ca,invalidateRows:J,invalidateAllRows:ia,updateCell:function(b,c){var a=ra(b,c);if(a){var d=h[c],e=L(b);p&&s===b&&z===c?p.loadValue(e):(a.innerHTML=e?Qa(b,d)(b,c,Y(e,d),d,e):"",A(b))}},updateRow:da,getViewport:y,getRenderedRange:v,resizeCanvas:$,updateRowCount:l,scrollRowIntoView:Lb,scrollRowToTop:function(b){la(b*d.rowHeight);
H()},scrollCellIntoView:Mb,getCanvasNode:function(){return Va},getViewportNode:function(){return Tb[0]},focus:eb,getCellFromPoint:wc,getCellFromEvent:Kb,getActiveCell:bd,setActiveCell:function(b,c){if(ua&&!(b>u()||0>b||c>=h.length||0>c)&&d.enableCellNavigation)Lb(b,!1),Mb(b,c),yb(ra(b,c),!1)},getActiveCellNode:function(){return w},getActiveCellPosition:dd,resetActiveCell:Nc,editActiveCell:ec,getCellEditor:function(){return p},getCellNode:ra,getCellNodeBox:function(b,c){if(!vc(b,c))return null;for(var a=
b*d.rowHeight-I,e=a+d.rowHeight-1,l=0,f=0;f<c;f++)l+=h[f].width;return{top:a,left:l,bottom:e,right:l+h[c].width}},canCellBeSelected:Jc,canCellBeActive:Ba,navigatePrev:Xc,navigateNext:Vc,navigateUp:Uc,navigateDown:dc,navigateLeft:Sc,navigateRight:Tc,gotoCell:Yc,getTopPanel:function(){return gd[0]},setTopPanelVisibility:function(b){d.showTopPanel!=b&&((d.showTopPanel=b)?db.slideDown("fast",$):db.slideUp("fast",$))},setHeaderRowVisibility:function(b){d.showHeaderRow!=b&&((d.showHeaderRow=b)?ib.slideDown("fast",
$):ib.slideUp("fast",$))},getHeaderRow:function(){return-1<d.frozenColumn?Wb:Wb[0]},getHeaderRowColumn:function(b){b=ga[b];var c;-1<d.frozenColumn?b<=d.frozenColumn?c=Ha:(c=nb,b-=d.frozenColumn+1):c=Ha;return(b=c.children().eq(b))&&b[0]},getGridPosition:function(){return hc(D[0])},flashCell:function(b,c,a){a=a||100;if(C[b]){var l=e(ra(b,c)),f=function(b){b&&setTimeout(function(){l.queue(function(){l.toggleClass(d.cellFlashingCssClass).dequeue();f(b-1)})},a)};f(4)}},addCellCssStyles:function(b,c){if(ma[b])throw"addCellCssStyles: cell CSS hash with key '"+
b+"' already exists.";ma[b]=c;uc(c,null);j(n.onCellCssStylesChanged,{key:b,hash:c})},setCellCssStyles:Kc,removeCellCssStyles:function(b){ma[b]&&(uc(null,ma[b]),delete ma[b],j(n.onCellCssStylesChanged,{key:b,hash:null}))},getCellCssStyles:function(b){return ma[b]},init:fb,destroy:function(){B().cancelCurrentEdit();j(n.onBeforeDestroy,{});for(var b=Ma.length;b--;)Pb(Ma[b]);d.enableColumnReorder&&M.sortable&&M.sortable("destroy");hb&&(hb.unbind("scroll."+aa),hb=null);D.unbind(".slickgrid");ab.remove();
bb=null;Va.unbind("draginit dragstart dragend drag");D.empty().removeClass(aa)},getEditorLock:B,getEditController:function(){return gc}});D=e(f);if(1>D.length)throw Error("SlickGrid requires a valid container, "+f+" does not exist in the DOM.");var Bc;if(!(Bc=a)){for(var Cc=1E6,Fd=e.browser.mozilla?6E6:1E9,Dc=e("<div style='display:none' />").appendTo(document.body);;){var ic=2*Cc;Dc.css("height",ic);if(ic>Fd||Dc.height()!==ic)break;else Cc=ic}Dc.remove();Bc=Cc}a=Bc;var Ec;if(!(Ec=g)){var Nb=e("<div style='position:absolute; top:-10000px; left:-10000px; width:100px; height:100px; overflow:scroll;'></div>").appendTo("body"),
Gd={width:Nb.width()-Nb[0].clientWidth,height:Nb.height()-Nb[0].clientHeight};Nb.remove();Ec=Gd}g=Ec;d=e.extend({},Ed,d);d.autoHeight&&(d.leaveSpaceForNewRows=!1);qc.width=d.defaultColumnWidth;for(var ga={},Ob=0;Ob<h.length;Ob++){var ta=h[Ob]=e.extend({},qc,h[Ob]);ga[ta.id]=Ob;ta.minWidth&&ta.width<ta.minWidth&&(ta.width=ta.minWidth);ta.maxWidth&&ta.width>ta.maxWidth&&(ta.width=ta.maxWidth)}if(d.enableColumnReorder&&!e.fn.sortable)throw Error("SlickGrid's 'enableColumnReorder = true' option requires jquery-ui.sortable module to be loaded");
gc={commitCurrentEdit:function(){var b=L(s),c=h[z];if(p){if(p.isValueChanged()){var a=p.validate();if(a.valid)return s<u()?(a={row:s,cell:z,editor:p,serializedValue:p.serializeValue(),prevSerializedValue:cd,execute:function(){this.editor.applyValue(b,this.serializedValue);da(this.row)},undo:function(){this.editor.applyValue(b,this.prevSerializedValue);da(this.row)}},d.editCommandHandler?(Ka(),d.editCommandHandler(b,c,a)):(a.execute(),Ka()),j(n.onCellChange,{row:s,cell:z,item:b})):(a={},p.applyValue(a,
p.serializeValue()),Ka(),j(n.onAddNewRow,{item:a,column:c})),!B().isActive();e(w).addClass("invalid");e(w).stop(!0,!0).effect("highlight",{color:"red"},300);j(n.onValidationError,{editor:p,cellNode:w,validationResults:a,row:s,cell:z,column:c});p.focus();return!1}Ka()}return!0},cancelCurrentEdit:function(){Ka();return!0}};D.empty().css("overflow","hidden").css("outline",0).addClass(aa).addClass("ui-widget");/relative|absolute|fixed/.test(D.css("position"))||D.css("position","relative");Vb=e("<div tabIndex='0' hideFocus style='position:fixed;width:0;height:0;top:0;left:0;outline:0;'></div>").appendTo(D);
lb=e("<div class='slick-pane slick-pane-header slick-pane-left' tabIndex='0' />").appendTo(D);mb=e("<div class='slick-pane slick-pane-header slick-pane-right' tabIndex='0' />").appendTo(D);Ga=e("<div class='slick-pane slick-pane-top slick-pane-left' tabIndex='0' />").appendTo(D);Na=e("<div class='slick-pane slick-pane-top slick-pane-right' tabIndex='0' />").appendTo(D);ya=e("<div class='slick-pane slick-pane-bottom slick-pane-left' tabIndex='0' />").appendTo(D);Oa=e("<div class='slick-pane slick-pane-bottom slick-pane-right' tabIndex='0' />").appendTo(D);
Gb=e("<div class='ui-state-default slick-header slick-header-left' />").appendTo(lb);Yb=e("<div class='ui-state-default slick-header slick-header-right' />").appendTo(mb);Ic=e("<div style='display:block;height:1px;position:absolute;top:0;left:0;'></div>").css("width",Bb()+g.width+"px").appendTo(ib);Ub=e().add(Gb).add(Yb);Fa=e("<div class='slick-header-columns slick-header-columns-left' style='left:-1000px' />").appendTo(Gb);Xa=e("<div class='slick-header-columns slick-header-columns-right' style='left:-1000px' />").appendTo(Yb);
M=e().add(Fa).add(Xa);Ya=e("<div class='ui-state-default slick-headerrow' />").appendTo(Ga);Fb=e("<div class='ui-state-default slick-headerrow' />").appendTo(Na);ib=e().add(Ya).add(Fb);Ha=e("<div class='slick-headerrow-columns slick-headerrow-columns-left' />").appendTo(Ya);nb=e("<div class='slick-headerrow-columns slick-headerrow-columns-right' />").appendTo(Fb);Wb=e().add(Ha).add(nb);zc=e("<div class='ui-state-default slick-top-panel-scroller' />").appendTo(Ga);Ac=e("<div class='ui-state-default slick-top-panel-scroller' />").appendTo(Na);
db=e().add(zc).add(Ac);hd=e("<div class='slick-top-panel' style='width:10000px' />").appendTo(zc);id=e("<div class='slick-top-panel' style='width:10000px' />").appendTo(Ac);gd=e().add(hd).add(id);d.showTopPanel||db.hide();d.showHeaderRow||ib.hide();U=e("<div class='slick-viewport slick-viewport-top slick-viewport-left' tabIndex='0' hideFocus />").appendTo(Ga);xa=e("<div class='slick-viewport slick-viewport-top slick-viewport-right' tabIndex='0' hideFocus />").appendTo(Na);fa=e("<div class='slick-viewport slick-viewport-bottom slick-viewport-left' tabIndex='0' hideFocus />").appendTo(ya);
Ia=e("<div class='slick-viewport slick-viewport-bottom slick-viewport-right' tabIndex='0' hideFocus />").appendTo(Oa);Tb=e().add(U).add(xa).add(fa).add(Ia);pa=e("<div class='grid-canvas grid-canvas-top grid-canvas-left' tabIndex='0' hideFocus />").appendTo(U);kb=e("<div class='grid-canvas grid-canvas-top grid-canvas-right' tabIndex='0' hideFocus />").appendTo(xa);wa=e("<div class='grid-canvas grid-canvas-bottom grid-canvas-left' tabIndex='0' hideFocus />").appendTo(fa);ob=e("<div class='grid-canvas grid-canvas-bottom grid-canvas-right' tabIndex='0' hideFocus />").appendTo(Ia);
Va=e().add(pa).add(kb).add(wa).add(ob);kc=Vb.clone().appendTo(D);d.explicitInitialization||fb()}}});var g,a})(jQuery);(function(e){e.extend(!0,window,{Slick:{Data:{DataView:function(g){function a(a){for(var d=a||0,e=x.length;d<e;d++){a=x[d][ba];if(void 0===a)throw"Each data element must implement a unique 'id' property";T[a]=d}}function f(){var a=J?Math.max(1,Math.ceil(da/J)):1;return{pageSize:J,pageNum:ca,totalRows:da,totalPages:a}}function m(d,e){B=e;Pa=d;$a=null;!1===e&&x.reverse();x.sort(d);!1===e&&x.reverse();T={};a();q()}function h(d,e){B=e;$a=d;Pa=null;var f=Object.prototype.toString;Object.prototype.toString=
"function"==typeof d?d:function(){return this[d]};!1===e&&x.reverse();x.sort();Object.prototype.toString=f;!1===e&&x.reverse();T={};a();q()}function d(){if(!va){va={};for(var a=0,d=O.length;a<d;a++)va[O[a][ba]]=a}}function fb(a){a=a.toString().match(/^function[^(]*\(([^)]*)\)\s*{([\s\S]*)}$/);return{params:a[1].split(","),body:a[2]}}function Pb(a,d){for(var e=[],f=0,g=0,h=a.length;g<h;g++)oa(a[g],d)&&(e[f++]=a[g]);return e}function Qb(a,d,e){for(var f=[],g=0,h,j=0,m=a.length;j<m;j++)h=a[j],e[j]?f[g++]=
h:oa(h,d)&&(f[g++]=h,e[j]=!0);return f}function Bb(a){va=null;if(N.isFilterNarrowing!=Za.isFilterNarrowing||N.isFilterExpanding!=Za.isFilterExpanding)u=[];if(oa){var d=g.inlineFilters?gb:Pb,e=g.inlineFilters?pb:Qb;N.isFilterNarrowing?X=d(X,Ca):N.isFilterExpanding?X=e(a,Ca,u):N.isFilterUnchanged||(X=d(a,Ca))}else X=J?a:a.concat();J?(X.length<ca*J&&(ca=Math.floor(X.length/J)),d=X.slice(J*ca,J*ca+J)):d=X;da=a=X.length;a=d;Y=[];if(null!=L){for(var d=a,f,h=[],j=[],m,q=0,x=d.length;q<x;q++)m=d[q],f=(f=
la?L(m):m[L])||0,e=j[f],e||(e=new Slick.Group,e.count=0,e.value=f,e.rows=[],h[h.length]=e,j[f]=e),e.rows[e.count++]=m;Y=h;if(Y.length){a=Y;for(d=a.length;d--;)e=a[d],e.collapsed=e.value in Ja,e.title=Qa?Qa(e):e.value;if(Aa){a=Y;for(d=a.length;d--;)if(e=a[d],!e.collapsed||ia){f=new Slick.GroupTotals;h=void 0;for(j=Aa.length;j--;)h=Aa[j],h.init(),Ra[j].call(h,e.rows),h.storeResult(f);f.group=e;e.totals=f}}Y.sort(Hb);a=Y;d=[];h=e=0;for(j=a.length;h<j;h++){f=a[h];d[e++]=f;if(!f.collapsed){m=0;for(q=f.rows.length;m<
q;m++)d[e++]=f.rows[m]}if(f.totals&&(!f.collapsed||ia))d[e++]=f.totals}a=d}}var d=O,e=a,B;f=[];j=0;h=e.length;N&&N.ignoreDiffsBefore&&(j=Math.max(0,Math.min(e.length,N.ignoreDiffsBefore)));N&&N.ignoreDiffsAfter&&(h=Math.min(e.length,Math.max(0,N.ignoreDiffsAfter)));q=j;for(x=d.length;q<h;q++)if(q>=x)f[f.length]=q;else if(j=e[q],m=d[q],L&&(B=j.__nonDataRow||m.__nonDataRow)&&j.__group!==m.__group||j.__updated||j.__group&&!j.equals(m)||Aa&&B&&(j.__groupTotals||m.__groupTotals)||j[ba]!=m[ba]||Da&&Da[j[ba]])f[f.length]=
q;O=a;return f}function q(){if(!j){var a=O.length,d=da,e=Bb(x,oa);J&&da<ca*J&&(ca=Math.max(0,Math.ceil(da/J)-1),e=Bb(x,oa));Da=null;Za=N;N={};d!=da&&$.notify(f(),null,Wa);a!=O.length&&Db.notify({previous:a,current:O.length},null,Wa);0<e.length&&Cb.notify({rows:e},null,Wa)}}var Wa=this,ba="id",x=[],O=[],T={},va=null,oa=null,Da=null,j=!1,B=!0,$a,Pa,N={},Za={},Ca,X=[],gb,pb,u=[],L,la,Qa,Hb,Y=[],Ja={},Aa,ia=!1,Ra,J=0,ca=0,da=0,Db=new Slick.Event,Cb=new Slick.Event,$=new Slick.Event;g=e.extend(!0,{},{groupItemMetadataProvider:null,
inlineFilters:!1},g);return{beginUpdate:function(){j=!0},endUpdate:function(){j=!1;q()},setPagingOptions:function(a){void 0!=a.pageSize&&(ca=(J=a.pageSize)?Math.min(ca,Math.max(0,Math.ceil(da/J)-1)):0);void 0!=a.pageNum&&(ca=Math.min(a.pageNum,Math.max(0,Math.ceil(da/J)-1)));$.notify(f(),null,Wa);q()},getPagingInfo:f,getItems:function(){return x},setItems:function(d,e){void 0!==e&&(ba=e);x=X=d;T={};a();for(var f,g=0,h=x.length;g<h;g++)if(f=x[g][ba],void 0===f||T[f]!==g)throw"Each data element must implement a unique 'id' property";
q()},setFilter:function(a){oa=a;if(g.inlineFilters){a=fb(oa);var d=a.body.replace(/return false[;}]/gi,"{ continue _coreloop; }").replace(/return true[;}]/gi,"{ _retval[_idx++] = $item$; continue _coreloop; }").replace(/return ([^;}]+?);/gi,"{ if ($1) { _retval[_idx++] = $item$; }; continue _coreloop; }"),d="var _retval = [], _idx = 0; var $item$, $args$ = _args; _coreloop: for (var _i = 0, _il = _items.length; _i < _il; _i++) { $item$ = _items[_i]; $filter$; } return _retval; ".replace(/\$filter\$/gi,
d),d=d.replace(/\$item\$/gi,a.params[0]),d=d.replace(/\$args\$/gi,a.params[1]);a=new Function("_items,_args",d);a.displayName=a.name="compiledFilter";gb=a;a=fb(oa);d=a.body.replace(/return false[;}]/gi,"{ continue _coreloop; }").replace(/return true[;}]/gi,"{ _cache[_i] = true;_retval[_idx++] = $item$; continue _coreloop; }").replace(/return ([^;}]+?);/gi,"{ if ((_cache[_i] = $1)) { _retval[_idx++] = $item$; }; continue _coreloop; }");d="var _retval = [], _idx = 0; var $item$, $args$ = _args; _coreloop: for (var _i = 0, _il = _items.length; _i < _il; _i++) { $item$ = _items[_i]; if (_cache[_i]) { _retval[_idx++] = $item$; continue _coreloop; } $filter$; } return _retval; ".replace(/\$filter\$/gi,
d);d=d.replace(/\$item\$/gi,a.params[0]);d=d.replace(/\$args\$/gi,a.params[1]);a=new Function("_items,_args,_cache",d);a.displayName=a.name="compiledFilterWithCaching";pb=a}q()},sort:m,fastSort:h,reSort:function(){Pa?m(Pa,B):$a&&h($a,B)},groupBy:function(a,d,e){g.groupItemMetadataProvider||(g.groupItemMetadataProvider=new Slick.Data.GroupItemMetadataProvider);L=a;la="function"===typeof L;Qa=d;Hb=e;Ja={};Y=[];q()},setAggregators:function(a,d){Aa=a;ia=void 0!==d?d:ia;Ra=[];for(var e=Aa.length;e--;){var f=
Ra,g=e,h=fb(Aa[e].accumulate),h=new Function("_items","for (var "+h.params[0]+", _i=0, _il=_items.length; _i<_il; _i++) {"+h.params[0]+" = _items[_i]; "+h.body+"}");h.displayName=h.name="compiledAccumulatorLoop";f[g]=h}q()},collapseGroup:function(a){Ja[a]=!0;q()},expandGroup:function(a){delete Ja[a];q()},getGroups:function(){return Y},getIdxById:function(a){return T[a]},getRowById:function(a){d();return va[a]},getItemById:function(a){return x[T[a]]},getItemByIdx:function(a){return x[a]},mapRowsToIds:function(a){for(var d=
[],e=0;e<a.length;e++)a[e]<O.length&&(d[d.length]=O[a[e]][ba]);return d},mapIdsToRows:function(a){var e=[];d();for(var f=0;f<a.length;f++){var g=va[a[f]];null!=g&&(e[e.length]=g)}return e},setRefreshHints:function(a){N=a},setFilterArgs:function(a){Ca=a},refresh:q,updateItem:function(a,d){if(void 0===T[a]||a!==d[ba])throw"Invalid or non-matching id";x[T[a]]=d;Da||(Da={});Da[a]=!0;q()},insertItem:function(d,e){x.splice(d,0,e);a(d);q()},addItem:function(d){x.push(d);a(x.length-1);q()},deleteItem:function(d){var e=
T[d];if(void 0===e)throw"Invalid id";delete T[d];x.splice(e,1);a(e);q()},syncGridSelection:function(a,d){var e=this,f=e.mapRowsToIds(a.getSelectedRows()),g;a.onSelectedRowsChanged.subscribe(function(){g||(f=e.mapRowsToIds(a.getSelectedRows()))});this.onRowsChanged.subscribe(function(){if(0<f.length){g=!0;var h=e.mapIdsToRows(f);d||(f=e.mapRowsToIds(h));a.setSelectedRows(h);g=!1}})},syncGridCellCssStyles:function(a,e){function f(a){g={};for(var d in a)g[O[d][ba]]=a[d]}var g,h;f(a.getCellCssStyles(e));
a.onCellCssStylesChanged.subscribe(function(a,d){h||e==d.key&&d.hash&&f(d.hash)});this.onRowsChanged.subscribe(function(){if(g){h=!0;d();var f={},j;for(j in g){var m=va[j];void 0!=m&&(f[m]=g[j])}a.setCellCssStyles(e,f);h=!1}})},getLength:function(){return O.length},getItem:function(a){return O[a]},getItemMetadata:function(a){a=O[a];return void 0===a?null:a.__group?g.groupItemMetadataProvider.getGroupRowMetadata(a):a.__groupTotals?g.groupItemMetadataProvider.getTotalsRowMetadata(a):g.groupItemMetadataProvider?
g.groupItemMetadataProvider.getRowMetadata(a):null},onRowCountChanged:Db,onRowsChanged:Cb,onPagingInfoChanged:$}},Aggregators:{Avg:function(e){this.field_=e;this.init=function(){this.sum_=this.nonNullCount_=this.count_=0};this.accumulate=function(a){a=a[this.field_];this.count_++;null!=a&&(""!=a&&NaN!=a)&&(this.nonNullCount_++,this.sum_+=parseFloat(a))};this.storeResult=function(a){a.avg||(a.avg={});0!=this.nonNullCount_&&(a.avg[this.field_]=this.sum_/this.nonNullCount_)}},Min:function(e){this.field_=
e;this.init=function(){this.min_=null};this.accumulate=function(a){a=a[this.field_];if(null!=a&&(""!=a&&NaN!=a)&&(null==this.min_||a<this.min_))this.min_=a};this.storeResult=function(a){a.min||(a.min={});a.min[this.field_]=this.min_}},Max:function(e){this.field_=e;this.init=function(){this.max_=null};this.accumulate=function(a){a=a[this.field_];if(null!=a&&(""!=a&&NaN!=a)&&(null==this.max_||a>this.max_))this.max_=a};this.storeResult=function(a){a.max||(a.max={});a.max[this.field_]=this.max_}},Sum:function(e){this.field_=
e;this.init=function(){this.sum_=null};this.accumulate=function(a){a=a[this.field_];null!=a&&(""!=a&&NaN!=a)&&(this.sum_+=parseFloat(a))};this.storeResult=function(a){a.sum||(a.sum={});a.sum[this.field_]=this.sum_}}}}}})})(jQuery);(function(e){e.extend(!0,window,{Slick:{Data:{GroupItemMetadataProvider:function(g){function a(a,d,e,f,h){return!g.enableExpandCollapse?h.title:"<span class='"+g.toggleCssClass+" "+(h.collapsed?g.toggleCollapsedCssClass:g.toggleExpandedCssClass)+"'></span>"+h.title}function f(a,d,e,f,g){return f.groupTotalsFormatter&&f.groupTotalsFormatter(g,f)||""}function m(a,d){var f=this.getDataItem(d.row);f&&(f instanceof Slick.Group&&e(a.target).hasClass(g.toggleCssClass))&&(f.collapsed?this.getData().expandGroup(f.value):
this.getData().collapseGroup(f.value),a.stopImmediatePropagation(),a.preventDefault())}function h(a){if(g.enableExpandCollapse&&a.which==e.ui.keyCode.SPACE){var d=this.getActiveCell();if(d&&(d=this.getDataItem(d.row))&&d instanceof Slick.Group)d.collapsed?this.getData().expandGroup(d.value):this.getData().collapseGroup(d.value),a.stopImmediatePropagation(),a.preventDefault()}}var d;g=e.extend(!0,{},{groupCssClass:"slick-group",totalsCssClass:"slick-group-totals",groupFocusable:!0,totalsFocusable:!1,
toggleCssClass:"slick-group-toggle",toggleExpandedCssClass:"expanded",toggleCollapsedCssClass:"collapsed",enableExpandCollapse:!0},g);return{init:function(a){d=a;d.onClick.subscribe(m);d.onKeyDown.subscribe(h)},destroy:function(){d&&(d.onClick.unsubscribe(m),d.onKeyDown.unsubscribe(h))},getRowMetadata:function(a){return g.getRowMetadata?g.getRowMetadata(a):null},getGroupRowMetadata:function(){return{selectable:!1,focusable:g.groupFocusable,cssClasses:g.groupCssClass,columns:{"0":{colspan:"*",formatter:a,
editor:null}}}},getTotalsRowMetadata:function(){return{selectable:!1,focusable:g.totalsFocusable,cssClasses:g.totalsCssClass,formatter:f,editor:null}}}}}}})})(jQuery);